version: '3.1'

services:

  db:
    image: mysql:8.0
#    env_file:
#      - src/main/resources/.env
    restart: always
    environment:
      MYSQL_HOST: "${MYSQL_HOST}"
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_DATABASE: "${MYSQL_DB_NAME}"
      MYSQL_USER: "${MYSQL_USERNAME}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD}"
    ports:
      - ${ACCESS_MYSQL_PORT}:${MYSQL_PORT}
#      - 3307:3306
    volumes:
      - db_data:/var/lib/mysql

  web:
    image: spring_boot_blog_api
#    env_file:
#      - src/main/resources/.env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${ACCESS_SERVER_PORT}:${SERVER_PORT}
#      - 8081:8080
    depends_on:
      - db
    environment:
      SERVER_PORT: ${SERVER_PORT}
      MYSQL_URL: "${MYSQL_URL}"
      MYSQL_DB_NAME: "${MYSQL_DB_NAME}"
      MYSQL_USERNAME: "${MYSQL_USERNAME}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_HOST: "${MYSQL_HOST}"
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_USE_SSL: "${MYSQL_USE_SSL}"
      MYSQL_ALLOW_PK: "${MYSQL_ALLOW_PK}"
      JWT_SECRET: "${JWT_SECRET}"
      ADMIN_EMAIL: "${ADMIN_EMAIL}"
      ADMIN_USERNAME: "${ADMIN_USERNAME}"
      ADMIN_PASSWORD: "${ADMIN_PASSWORD}"

volumes:
  db_data: {}